name: Add Build Output To Release
on:
  workflow_dispatch:
    inputs:
      artifactUrl:
        description: Artifact URL - The URL of the build artifact hosted on EAS. From the build payload result this is `artifacts.buildUrl` (if the build is successful.)
        required: true
        type: string
      appVersion:
        description: App Version - The "version name" aka "marketing version" of the app. It should match an already existing release.
        required: true
        type: string

jobs:
  download_eas_build:
    runs-on: ubuntu-latest
    environment: production
    name: Download EAS Build and Add To Release
    permissions:
      contents: read
    steps:
      - name: Run cURL script to download
        run: |
          curl -sSL ${{ inputs.artifactUrl }} -o ${{ inputs.appVersion }}.aab

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aab-file
          path: ${{ inputs.appVersion }}.aab
          retention-days: 1

  create_and_upload_artifacts:
    runs-on: ubuntu-latest
    environment: production
    needs: [download_eas_build]
    name: Create and Upload Artifacts
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Bundletool
        uses: amyu/setup-bundletool@v1

      - name: Get AAB Artifact
        uses: actions/download-artifact@v4
        with:
          name: aab-file

      - name: Test
        run: ls -lha

      # - name: Generate APK for F-Droid
      #   id: convert_aab
      #   uses: mukeshsolanki/bundletool-action@v1.0.2
      #   with:
      #     aabFile: ${{ inputs.appVersion }}.aab
      #     base64Keystore: ${{ secrets.APP_JKS }}
      #     keystorePassword: ${{ secrets.APP_KS_PWD }}
      #     keystoreAlias: ${{ secrets.APP_KS_KEY_ALS }}
      #     keyPassword: ${{ secrets.APP_KS_KEY_PWD }}

      # - name: Add Build To Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       ${{ inputs.appVersion }}.aab
      #       ${{ steps.convert_aab.outputs.apkPath }}
