name: Trigger Expo Build (iOS)
on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set eas.json file - EXPO_PUBLIC_SETLISTFM_API_KEY
        uses: jossef/action-set-json-field@v2.2
        with:
          file: eas.json
          field: build.production.env.EXPO_PUBLIC_SETLISTFM_API_KEY
          value: ${{ secrets.EXPO_PUBLIC_SETLISTFM_API_KEY }}

      - name: Set eas.json file - EXPO_PUBLIC_SPOTIFY_API_KEY
        uses: jossef/action-set-json-field@v2.2
        with:
          file: eas.json
          field: build.production.env.EXPO_PUBLIC_SPOTIFY_API_KEY
          value: ${{ secrets.EXPO_PUBLIC_SPOTIFY_API_KEY }}

      - name: Set eas.json file - EXPO_PUBLIC_APPLE_MUSIC_DEV_TOKEN_ENDPOINT
        uses: jossef/action-set-json-field@v2.2
        with:
          file: eas.json
          field: build.production.env.EXPO_PUBLIC_APPLE_MUSIC_DEV_TOKEN_ENDPOINT
          value: ${{ secrets.EXPO_PUBLIC_APPLE_MUSIC_DEV_TOKEN_ENDPOINT }}

      - name: Build app
        run: eas build -p ios --non-interactive --no-wait -m="GitHub Actions - Run $GITHUB_RUN_ID"
